/**
 * Honest end-to-end test: 2 segments → Hyperframes clips → FFmpeg final MP4.
 *
 * The TTS word timings below are SYNTHETIC fixtures (clearly labeled) —
 * in production they come from the real TTS service. Everything else is
 * real: the narration WAVs are generated by FFmpeg (silent, exact
 * durations), the segment clips are rendered by headless Chrome via the
 * Hyperframes CLI, and the final MP4 is muxed by FFmpeg.
 *
 * Skips gracefully (never fakes a pass) when FFmpeg or the Hyperframes
 * browser is unavailable in the environment.
 *
 * Run: npm test (dentro do pacote video).
 * Takes ~1–3 minutes when the browser is present.
 */
import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';
import type { Segment, Spec } from '@shorts-forge/shared';
import { renderJobSegments, assembleJob } from '../index.js';

const workdir = mkdtempSync(join(process.cwd(), '.e2e-render-'));
after(() => {
  rmSync(workdir, { recursive: true, force: true });
});

function ffmpegOk(): boolean {
  try {
    const res = spawnSync('ffmpeg', ['-hide_banner', '-version'], { timeout: 10_000 });
    return res.status === 0;
  } catch {
    return false;
  }
}

/**
 * Generates a synthetic narration WAV of exactly `durationSec` (a sine
 * tone — synthetic, but with real audio energy like actual TTS speech;
 * pure digital silence would break `loudnorm`, which cannot normalize
 * -inf LUFS).
 */
function makeToneWav(outPath: string, durationSec: number): void {
  const res = spawnSync(
    'ffmpeg',
    [
      '-hide_banner', '-y',
      '-f', 'lavfi', '-i', `sine=frequency=196:duration=${durationSec}`,
      '-ar', '48000', '-ac', '2',
      '-c:a', 'pcm_s16le',
      outPath,
    ],
    { timeout: 60_000, encoding: 'utf8' },
  );
  if (res.status !== 0 || !existsSync(outPath)) {
    throw new Error(`falha a gerar WAV de teste: ${String(res.stderr).slice(-500)}`);
  }
}

function ffprobeStreams(mp4: string): { vcodec: string; acodec: string; width: number; height: number; duration: number } {
  const res = spawnSync(
    'ffprobe',
    [
      '-hide_banner', '-v', 'error',
      '-select_streams', 'v:0', '-show_entries', 'stream=codec_name,width,height',
      '-show_entries', 'format=duration',
      '-of', 'json',
      mp4,
    ],
    { timeout: 30_000, encoding: 'utf8' },
  );
  if (res.status !== 0) throw new Error(`ffprobe falhou: ${String(res.stderr).slice(-500)}`);
  const parsed = JSON.parse(String(res.stdout)) as {
    streams: Array<{ codec_name: string; width: number; height: number }>;
    format: { duration: string };
  };
  const audio = spawnSync(
    'ffprobe',
    ['-hide_banner', '-v', 'error', '-select_streams', 'a:0', '-show_entries', 'stream=codec_name', '-of', 'csv=p=0', mp4],
    { timeout: 30_000, encoding: 'utf8' },
  );
  return {
    vcodec: parsed.streams[0]?.codec_name ?? '',
    acodec: String(audio.stdout ?? '').trim(),
    width: parsed.streams[0]?.width ?? 0,
    height: parsed.streams[0]?.height ?? 0,
    duration: Number(parsed.format.duration),
  };
}

/** Synthetic TTS fixture — in production these come from the real TTS. */
function syntheticSegment(
  id: string,
  words: Array<{ word: string; start: number; end: number }>,
  breathMarginSec: number,
  narrationWav: string,
): Segment {
  const lastEnd = Math.max(...words.map((w) => w.end));
  const seg: Segment = {
    id,
    narration: words.map((w) => w.word).join(' '),
    visualKeywords: ['teste'],
    brollDescription: 'fundo de teste',
    targetDurationSec: lastEnd + breathMarginSec,
    tts: { audioPath: narrationWav, words, durationSec: lastEnd },
    actualDurationSec: lastEnd + breathMarginSec,
  };
  if (id === 'seg-01') seg.hookLine = 'Isto muda tudo';
  return seg;
}

test('e2e: 2 segmentos → clips Hyperframes → final.mp4 com áudio', async (t) => {
  if (!ffmpegOk()) {
    t.skip('ffmpeg indisponível neste ambiente — e2e de montagem impossível');
    return;
  }

  const audioDir = join(workdir, 'audio');
  mkdirSync(audioDir, { recursive: true });
  const wav1 = join(audioDir, 'seg-01.wav');
  const wav2 = join(audioDir, 'seg-02.wav');
  makeToneWav(wav1, 2.0);
  makeToneWav(wav2, 2.5);

  const spec: Spec = {
    version: 1,
    title: 'E2E de teste',
    format: '9:16',
    language: 'pt-PT',
    segments: [
      syntheticSegment(
        'seg-01',
        [
          { word: 'Olá', start: 0.2, end: 0.6 },
          { word: 'mundo', start: 0.6, end: 1.1 },
          { word: 'do', start: 1.1, end: 1.3 },
          { word: 'teste', start: 1.3, end: 1.9 },
        ],
        0.25,
        wav1,
      ),
      syntheticSegment(
        'seg-02',
        [
          { word: 'Segunda', start: 0.1, end: 0.7 },
          { word: 'parte', start: 0.7, end: 1.2 },
          { word: 'do', start: 1.2, end: 1.4 },
          { word: 'vídeo', start: 1.4, end: 2.0 },
          { word: 'final', start: 2.0, end: 2.4 },
        ],
        0.25,
        wav2,
      ),
    ],
  };

  // 1. Per-segment Hyperframes renders (skip gracefully without browser).
  let clips: string[];
  try {
    clips = await renderJobSegments(spec, {
      outDir: join(workdir, 'segments'),
      format: '9:16',
      template: 'bold-social',
    });
  } catch (err) {
    t.skip(
      `render Hyperframes indisponível neste ambiente (browser do hyperframes em falta?): ${err instanceof Error ? err.message.split('\n')[0] : String(err)}`,
    );
    return;
  }
  assert.equal(clips.length, 2);
  for (const clip of clips) assert.ok(existsSync(clip), `clip existe: ${clip}`);

  // 2. FFmpeg assembly of the real clips + real narration audio.
  const finalMp4 = await assembleJob({
    segments: spec.segments,
    segmentClips: clips,
    outDir: join(workdir, 'final'),
    format: '9:16',
  });
  assert.ok(existsSync(finalMp4), 'final.mp4 existe');
  assert.ok(finalMp4.endsWith('final.mp4'));

  // 3. Probe the result: h264 1080x1920 + aac, ~5s total.
  const probed = ffprobeStreams(finalMp4);
  assert.equal(probed.vcodec, 'h264');
  assert.equal(probed.width, 1080);
  assert.equal(probed.height, 1920);
  assert.equal(probed.acodec, 'aac');
  assert.ok(
    Math.abs(probed.duration - 5.0) < 0.6,
    `duração ~5.0s (obtida: ${probed.duration})`,
  );
});
